### PR TITLE
Rejection Sampler for Archimedean Spiral

### PR DESCRIPTION
**Pull request by 20demkowiczbr**
This branch contains a function, `sample_arch_spiral()`, that performs a uniform sample of an archimedean spiral with however many wraps the user desires. Documentation and examples included.

### CODE REVIEW

**Comment by corybrunson** [comment]
Nice! As usual, a few requests:
* The example with `n = 720` and `max_wrap = 2` is helpful, but some experimentation leads me to think that an example with fewer points and more laps would better illustrate the uniformity of the sample to a new user. What do you think? Maybe include two examples if you think the current one is also important.
* Please auto-wrap the comments in the script to a maximum width of 80 characters. : )
* Since you're familiar with the Archimedian spiral now, could you add a few sentences of description? It would also be good to include a citation for the specific parameterization used.

**Comment by 20demkowiczbr** [comment]
> Nice! As usual, a few requests:
> 
> * The example with `n = 720` and `max_wrap = 2` is helpful, but some experimentation leads me to think that an example with fewer points and more laps would better illustrate the uniformity of the sample to a new user. What do you think? Maybe include two examples if you think the current one is also important.
> * Please auto-wrap the comments in the script to a maximum width of 80 characters. : )
> * Since you're familiar with the Archimedian spiral now, could you add a few sentences of description? It would also be good to include a citation for the specific parameterization used.

This is the website from which I obtained the parametrization: http://www.mathematische-basteleien.de/spiral.htm.

Is it okay to just insert a url into the `@details`? If not, how would I reference it in the style we used for Arvo, Diaconis, etc?

**Comment by corybrunson** [comment]
Everything looks good! We discussed noise yesterday, which can wait until the remaining merges are completed so that they can all be handled at once. The only missing detail is the citation for the archimedian spiral, which we also discussed yesterday.

I've added a warning to the original spiral sampler i wrote (adapted from [KODAMA](https://cran.r-project.org/package=KODAMA)), which was archimedian but not uniformly sampled. Some time later, one of us should give your uniform sampler the option of producing multiple spirals, the way the original was intended to do.

**Comment by 20demkowiczbr** [comment]
> Everything looks good! We discussed noise yesterday, which can wait until the remaining merges are completed so that they can all be handled at once. The only missing detail is the citation for the archimedian spiral, which we also discussed yesterday.
> 
> I've added a warning to the original spiral sampler i wrote (adapted from [KODAMA](https://cran.r-project.org/package=KODAMA)), which was archimedian but not uniformly sampled. Some time later, one of us should give your uniform sampler the option of producing multiple spirals, the way the original was intended to do.

Citation created.

**Pull request merged**
