### PR TITLE
Figure8

### PR DESCRIPTION
**Pull request by 20demkowiczbr**
This branch contains a function, `sample_figure_eight()`, to uniformly sample a figure eight using jacobians to counteract any warping during sampling. Full documentation is included.

### CODE REVIEW

**Comment by corybrunson** [comment]
@20demkowiczbr i added a version of my naïve sampler to the example file, so users can see the (small but perceptible) difference between the results. Does that look OK to you?

If so, i have two additional requests before completing the merge:
1. Following the pattern of other functions that use rejection sampling, for example those in `circles.r`, please add noise functionality to your figure eight sampler.
2. To avoid confusion, remove my naïve sampler (in `circles.r`) and the example that uses it (in `ex-circles.r`).

Thanks!

**Comment by 20demkowiczbr** [comment]
> @20demkowiczbr i added a version of my naïve sampler to the example file, so users can see the (small but perceptible) difference between the results. Does that look OK to you?
> 
> If so, i have two additional requests before completing the merge:
> 
> 1. Following the pattern of other functions that use rejection sampling, for example those in `circles.r`, please add noise functionality to your figure eight sampler.
> 2. To avoid confusion, remove my naïve sampler (in `circles.r`) and the example that uses it (in `ex-circles.r`).
> 
> Thanks!

Should be all set!

**Comment by corybrunson** [comment]
@20demkowiczbr the updates look good!

I apologize, but i also missed something in the original PR (pull request): An aspect ratio parameter is included, but its effect is to scale both of the coordinates. This is unnecessary, because a user can multiply the finished product by the same scale factor. The purpose, for some functions, of having an aspect ratio is to control the ratio between two measurements of the shape, for example the "inner" and "outer" radii of an embedded torus, that cannot be easily adjusted after generating the sample.

Now that i think of it, it _might_ be unnecessary for the Archimedian spirals as well—we can check tomorrow. In the meantime, could you excise this feature from the figure eight sampler?

**Comment by 20demkowiczbr** [comment]
> @20demkowiczbr the updates look good!
> 
> I apologize, but i also missed something in the original PR (pull request): An aspect ratio parameter is included, but its effect is to scale both of the coordinates. This is unnecessary, because a user can multiply the finished product by the same scale factor. The purpose, for some functions, of having an aspect ratio is to control the ratio between two measurements of the shape, for example the "inner" and "outer" radii of an embedded torus, that cannot be easily adjusted after generating the sample.
> 
> Now that i think of it, it _might_ be unnecessary for the Archimedian spirals as well—we can check tomorrow. In the meantime, could you excise this feature from the figure eight sampler?

Aspect ratio was removed from figure eight function.

**Comment by corybrunson** [comment]
Great—i just added the universal default `sd = 0`. Will merge once the checks are done!

**Pull request merged**
